# Generated by Django 4.1.5 on 2023-01-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklepgier', '0002_akcesoria_figurki_podreczniki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akcesoria',
        ),
        migrations.DeleteModel(
            name='Figurki',
        ),
        migrations.DeleteModel(
            name='Podreczniki',
        ),
    ]
