# Generated by Django 4.1.5 on 2023-01-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepgier', '0003_delete_akcesoria_delete_figurki_delete_podreczniki'),
    ]

    operations = [
        migrations.CreateModel(
            name='lol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
